src/web/src/main/java/DOM/AdminManagedBean.java
package DOM;

import java.io.Serializable;
import java.util.List;
import java.io.*;

import org.apache.log4j.Logger;
import org.hibernate.Session;
import org.hibernate.Transaction;

import hbm.Admin;
import util.HibernateUtil;

public class AdminManagedBean implements Serializable
{

    private static final long serialVersionUID = 1L;
    private static Logger log = Logger.getLogger(AdminManagedBean.class);
    private static final String SUCCESS = "success";
    private static final String ERROR   = "error";

    private String adminPass;
    private String isAdminPass;


    public String getAdminPass()
    {
        return adminPass;
    }

    public void setAdminPass(String adminPass)
    {
        this.adminPass = adminPass;
    }

    public String getIsAdminPass()
    {
        return isAdminPass;
    }

    public void setIsAdminPass(String isAdminPass)
    {
        this.isAdminPass = isAdminPass;
    }


    public String save()
    {
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        Admin admin = new Admin();

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(admin);
            tx.commit();
            log.debug("Nuevo registro : " + admin + ", realizado : " +
                    tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public List<Admin> getAdmins()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<Admin>  adminList =
            session.createCriteria(Admin.class).list();
        return adminList;
    }

    public void reset()
    {
    }









    public void checkAdminPassword()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Admin admin = (Admin) session.load(Admin.class, 1);

        if (this.getAdminPass().equals(admin.getPassword()))
        {
            this.isAdminPass = "si";
        }
        else
        {
            this.isAdminPass = "no";
        }
    }
}

src/web/src/main/java/DOM/EmpleadoManagedBean.java
package DOM;

import java.io.Serializable;
import java.util.List;
import java.io.*;

import org.apache.log4j.Logger;
import org.hibernate.Session;
import org.hibernate.Transaction;

import hbm.Empleado;
import util.HibernateUtil;

public class EmpleadoManagedBean implements Serializable
{

    private static final long serialVersionUID = 1L;
    private static Logger log = Logger.getLogger(EmpleadoManagedBean.class);
    private static final String SUCCESS = "success";
    private static final String ERROR   = "error";
    private String empleado;
    private String cedula;
    private String nombre;
    private String password;

    private String isPass;

    private Empleado empleadoO;

    private List<Empleado> filteredEmpleados;

    public List<Empleado> getFilteredEmpleados() {
        return filteredEmpleados;
    }

    public void setFilteredEmpleados(List<Empleado> filteredEmpleados) {
        this.filteredEmpleados = filteredEmpleados;
    }

    public Empleado getEmpleadoO()
    {
        return empleadoO;
    }

    public void setEmpleadoO(Empleado empleadoO)
    {
        this.empleadoO = empleadoO;
    }

    public String getEmpleado()
    {
        return this.empleado;
    }
    public void setEmpleado(String empleado)
    {
        this.empleado = empleado;
    }

    public String getCedula()
    {
        return this.cedula;
    }

    public String getNombre()
    {
        return this.nombre;
    }

    public void setCedula(String cedula)
    {
        this.cedula = cedula;
    }

    public void setNombre(String nombre)
    {
        this.nombre = nombre;
    }

    public String getPassword()
    {
        return password;
    }

    public void setPassword(String password)
    {
        this.password = password;
    }

    public String getIsPass()
    {
        return isPass;
    }

    public void setIsPass(String isPass)
    {
        this.isPass = isPass;
    }


    public String save()
    {
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        Empleado empleado = new Empleado();
        empleado.setCedula(this.getCedula());
        empleado.setNombre(this.getNombre());
        empleado.setPassword(this.getPassword());

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(empleado);
            tx.commit();
            log.debug("Nuevo registro : " + empleado + ", realizado : " +
                    tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public List<Empleado> getEmpleados()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<Empleado>  empleadoList =
            session.createCriteria(Empleado.class).list();
        return empleadoList;
    }

    public void reset()
    {
        this.setCedula("");
        this.setNombre("");
        this.setPassword("");
    }






    public int getIdEmpleado(String cedula)
    {
        List<Empleado> empleados = getEmpleados();

        for (Empleado empleado : empleados)
        {
            if (empleado.getCedula().equals(cedula))
            {
                return empleado.getId();
            }
        }

        return 0;
    }

    public void checkEmpleadoPassword()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Empleado empleado = (Empleado) session.load(Empleado.class,
                getIdEmpleado(this.getCedula()));

        if (this.getPassword().equals(empleado.getPassword()))
        {
            this.isPass = "si";
        }
        else
        {
            this.isPass = "no";
        }
    }


    public void onEmpleadoChange()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Empleado empleado = (Empleado) session.load(Empleado.class,
                this.getIdEmpleado(this.getEmpleado()));

        this.setCedula(empleado.getCedula());
        this.setNombre(empleado.getNombre());
        this.setPassword(empleado.getPassword());
    }

    public void onEmpleadoChangeT()
    {
        this.setEmpleado(this.getEmpleadoO().getCedula());
        this.onEmpleadoChange();
    }


    public String modificar()
    {
        this.setEmpleado(this.getEmpleadoO().getCedula());
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();
        Empleado empleado = (Empleado) session.load(Empleado.class,
                this.getIdEmpleado(this.getEmpleado()));

        empleado.setCedula(this.getCedula());
        empleado.setNombre(this.getNombre());
        empleado.setPassword(this.getPassword());

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(empleado);
            tx.commit();
            log.debug("Nuevo registro : " + empleado + ", realizado : " +
                      tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }
}

src/web/src/main/java/DOM/FacturaManagedBean.java
package DOM;

import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.Map;
import java.util.HashMap;

import org.apache.log4j.Logger;
import org.hibernate.Session;
import org.hibernate.Transaction;

import hbm.Factura;
import hbm.Cliente;
import hbm.Guia;
import util.HibernateUtil;

public class FacturaManagedBean implements Serializable
{

    private static final long serialVersionUID = 1L;
    private static Logger log = Logger.getLogger(FacturaManagedBean.class);
    private static final String SUCCESS = "success";
    private static final String ERROR   = "error";

    private String ruc_empresa;
    private int id_cliente;
    private Date fecha;
    private float valor;
    private boolean pagado;
    private String factura;
    private String empresa;
    private List<Guia> guiasFactura = new ArrayList<Guia>();



    private Factura facturaO;

    private List<Factura> filteredFacturas;

    public List<Factura> getFilteredFacturas() {
        return filteredFacturas;
    }

    public void setFilteredFacturas(List<Factura> filteredFacturas) {
        this.filteredFacturas = filteredFacturas;
    }

    public Factura getFacturaO()
    {
        return facturaO;
    }

    public void setFacturaO(Factura facturaO)
    {
        this.facturaO = facturaO;
    }



    public String getRuc_empresa()
    {
        return this.ruc_empresa;
    }

    public void setRuc_empresa(String ruc_empresa)
    {
        this.ruc_empresa = ruc_empresa;
    }

    public int getId_cliente()
    {
        return this.id_cliente;
    }

    public void setId_cliente(int id_cliente)
    {
        this.id_cliente = id_cliente;
    }

    public void setFecha(Date fecha)
    {
        this.fecha = fecha;
    }

    public Date getFecha()
    {
        return fecha;
    }

    public void setValor(float valor)
    {
        this.valor = valor;
    }

    public float getValor()
    {
        return this.valor;
    }

    public void setPagado(boolean pagado)
    {
        this.pagado = pagado;
    }

    public boolean getPagado()
    {
        return this.pagado;
    }

    public String getFactura()
    {
        return this.factura;
    }

    public void setFactura(String factura)
    {
        this.factura = factura;
    }

    public String getEmpresa()
    {
        return this.empresa;
    }

    public void setEmpresa(String empresa)
    {
        this.empresa = empresa;
    }

    public void setGuiasFactura(List<Guia> guiasFactura)
    {
        this.guiasFactura = guiasFactura;
    }

    public List<Guia> getGuiasFactura()
    {
        return guiasFactura;
    }


    public String save()
    {
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        // Cliente
        ClienteManagedBean cmb = new ClienteManagedBean();
        Cliente cliente = (Cliente) session.load(Cliente.class,
                cmb.getIdCliente(this.getRuc_empresa()));


        Factura factura = new Factura();
        factura.setFecha(new Date());
        factura.setValor(this.getValor());
        factura.setPagado(false);
        factura.setCliente(cliente);

        // Agregar factura al cliente
        cliente.getFacturas().add(factura);

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(factura);
            tx.commit();
            log.debug("Nuevo registro : " + factura + ", realizado : " + tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public List<Factura> getFacturas()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<Factura>  facturaList = session.createCriteria(Factura.class).list();
        return facturaList;
    }

    public List<Factura> getFacturasPendientes()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<Factura>  facturaList = session.createCriteria(Factura.class).list();
        List<Factura> facturaPendList = new ArrayList<Factura>();
        for (Factura f : facturaList)
        {
            if (!f.isPagado())
            {
                facturaPendList.add(f);
            }
        }
        return facturaPendList;
    }

    public void reset()
    {
        this.setFecha(new Date());
        this.setValor(0);
        this.setPagado(false);
    }









    public String pagar()
    {
        this.setFactura(String.valueOf(this.getFacturaO().getId()));
        String result = null;
        Session session = HibernateUtil.getSessionFactory().openSession();

        Factura factura = (Factura) session.load(Factura.class,
                Integer.parseInt(this.getFactura()));

        factura.setPagado(true);

        Transaction tx = null;

        try
        {
            tx = session.beginTransaction();
            session.save(factura);
            tx.commit();
            log.debug("Nuevo registro : " + factura + ", realizado : " +
                      tx.wasCommitted());
            result = SUCCESS;
        }
        catch (Exception e)
        {
            if (tx != null)
            {
                tx.rollback();
                result = ERROR;
                e.printStackTrace();
            }
        }
        finally
        {
            session.close();
        }
        return result;
    }

    public Map<String, String> getUnpaidFacturas()
    {
        List<Factura> facturaList = this.getFacturas();
        Map<String, String> descripciones = new  HashMap<String, String>();

        for (Factura f : facturaList)
        {
            if (!f.isPagado())
            {
                descripciones.put(f.getCliente().getNombre_empresa() + " | $" +
                        Float.toString(f.getValor()),
                        Integer.toString(f.getId()));
            }
        }

        return descripciones;
    }

    public Map<String, String> getFacturasDescripcion()
    {
        List<Factura> facturaList = this.getFacturas();
        Map<String, String> descripciones = new  HashMap<String, String>();

        for (Factura f : facturaList)
        {
            descripciones.put(f.getCliente().getNombre_empresa() + " | $" +
                    Float.toString(f.getValor()), Integer.toString(f.getId()));

        }

        return descripciones;
    }

    public void onFacturaChange()
    {
        Session session = HibernateUtil.getSessionFactory().openSession();
        Factura factura = (Factura) session.load(Factura.class,
                Integer.parseInt(this.getFactura()));

        List<Guia> guias = new ArrayList<Guia>();
        guias.addAll(factura.getGuias());

        this.setFecha(factura.getFecha());
        this.setEmpresa(factura.getCliente().getNombre_empresa());
        this.setValor(factura.getValor());
        this.setPagado(factura.isPagado());
        this.setGuiasFactura(guias);
    }

    public void onFacturaChangeT()
    {
        this.setFactura(String.valueOf(this.getFacturaO().getId()));
        this.onFacturaChange();
    }
}

src/web/src/main/webapp/agregar-cliente.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">

 <h:head><title>Paqueteria</title></h:head>
 <body>
    <p:panel header="Nuevo Cliente">
    <h:form>
         <table>
             <tr>
                <td><h:outputLabel for="ruc_empresa" value="Ruc empresarial:" /></td>
                <td><p:inputText id="ruc_empresa" value="#{clienteMBean.ruc_empresa}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="nombre_empresa" value="Nombre empresa:" /></td>
                <td><p:inputText id="nombre_empresa" value="#{clienteMBean.nombre_empresa}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="cedula_representante" value="Cedula representante:" /></td>
                <td><p:inputText id="cedula_representante" value="#{clienteMBean.cedula_representante}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="nombre_representante" value="Nombre representante:" /></td>
                <td><p:inputText id="nombre_representante" value="#{clienteMBean.nombre_representante}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="telefono" value="Teléfono:" /></td>
                <td><p:inputText id="telefono" value="#{clienteMBean.telefono}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="direccion" value="Dirección:" /></td>
                <td><p:inputText id="direccion" value="#{clienteMBean.direccion}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="password" value="Contraseña:" /></td>
                <td><p:inputText id="password" value="#{clienteMBean.password}"/></td>
             </tr>


             <tr>
                <td><p:commandButton id="submit" value="Guardar" action="#{clienteMBean.save()}" ajax="false"/></td>
                <td><p:commandButton id="reset" value="Resetear" action="#{clienteMBean.reset()}" ajax="false"/></td>
             </tr>
         </table>
     </h:form>
     </p:panel>
</body>
</html>

src/web/src/main/webapp/agregar-evento.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">

 <h:head><title>Paqueteria</title></h:head>
 <body>
    <p:panel header="Agregar Evento">
        <h:form id="main">


        <p:dataTable id="guia" var="guia"
            value="#{guiaMBean.guias}"
            widgetVar="guiasTable" emptyMessage="Guias no encontrados con
            ese criterio" filteredValue="#{eventoMBean.filteredGuias}"
            rows="20" paginator="true" paginatorTemplate="{CurrentPageReport}
            {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink}
            {LastPageLink} {RowsPerPageDropdown}"
            rowsPerPageTemplate="5,10,20,50"
            resizableColumns="false" liveResize="true" selectionMode="single"
            selection="#{eventoMBean.guiaO}" rowKey="#{guia.id}">

            <f:facet name="header">
                <p:outputPanel>
                    <h:outputText value="Guia" />
                    <br/>
                    <br/>
                    <h:outputText value="Buscar en todos los campos:  " />
                    <p:inputText id="globalFilter"
                        onkeyup="PF('guiasTable').filter()"
                        style="width:150px" placeholder="Ingrese palabara"/>
                </p:outputPanel>
            </f:facet>

            <p:column filterBy="#{guia.cliente.ruc_empresa}" headerText="Ruc Empresa"  filterMatchMode="contains">
                    <h:outputText value="#{guia.cliente.ruc_empresa}" />
            </p:column>
            <p:column filterBy="#{guia.cliente.nombre_empresa}" headerText="Empresa"  filterMatchMode="contains">
                    <h:outputText value="#{guia.cliente.nombre_empresa}" />
            </p:column>
            <p:column filterBy="#{guia.ruta.getDescripcion()}" headerText="Ruta"  filterMatchMode="contains">
                <h:outputText value="#{guia.ruta.getDescripcion()}" />
            </p:column>
            <p:column filterBy="#{guia.paquete.getDescripcion()}" headerText="Paquete"  filterMatchMode="contains">
                <h:outputText value="#{guia.paquete.getDescripcion()}" />
            </p:column>
            <p:column filterBy="#{guia.detalle}" headerText="Detalle"  filterMatchMode="contains">
                <h:outputText value="#{guia.detalle}" />
            </p:column>
        </p:dataTable>



            <br/>
            <hr/>
            <br/>
            <p:outputLabel for="evento" value="Evento:" />
            <p:selectOneRadio id="evento" value="#{eventoMBean.evento}">
                <br/>
                <f:selectItem itemLabel="Salida" itemValue="Salida"/>
                <br/>
                <f:selectItem itemLabel="Llegada" itemValue="Llegada"/>
                <br/>
                <f:selectItem itemLabel="Entregado" itemValue="Entregado"/>
                <br/>
                <f:selectItem itemLabel="Aprobado" itemValue="Aprobado"/>
                <br/>
                <f:selectItem itemLabel="Rechazado" itemValue="Rechazado"/>
                <br/>
                <f:selectItem itemLabel="Retornado" itemValue="Retornado"/>
                <br/>
                <f:selectItem itemLabel="Punto de control" itemValue="Punto de
                control"/>
            </p:selectOneRadio>


            <br/>
            <hr/>
            <br/>
            <h:outputLabel for="descripcion" value="Descripción [opcional]:" />
            <p:inputText id="descripcion" value="#{eventoMBean.descripcion}"/>


            <br/>
            <hr/>
            <br/>
            <p:commandButton id="submit" value="Guardar" action="#{eventoMBean.save()}" ajax="false"/>
            <p:commandButton id="reset" value="Resetear" action="#{eventoMBean.reset()}" ajax="false"/>

     </h:form>
     </p:panel>
</body>
</html>

src/web/src/main/webapp/agregar-factura.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">

 <h:head><title>Paqueteria</title></h:head>
 <body>

        <h1>
            Esta pagina es usada unicamente como mecanismo de pruebas manual.
            Las facturas deben ser creadas de forma automatica durante la
            transacción de un nuevo envio!
        </h1><br/><br/>


    <p:panel header="Agregar Factura">
    <h:form>
         <table>
             <tr>
                 <td>La fecha será la fecha actual<br/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="ruc_empresa" value="Ruc Empresa:" /></td>
                <td><p:inputText id="ruc_empresa" value="#{facturaMBean.ruc_empresa}"/></td>
             </tr>
             <tr>
                <td><h:outputLabel for="valor" value="Valor:" /></td>
                <td><p:inputText id="valor" value="#{facturaMBean.valor}"/></td>
             </tr>
             <tr>
                 <td><br/>El estado de pagado sera «falso»</td>
             </tr>


             <tr>
                <td><p:commandButton id="submit" value="Guardar" action="#{facturaMBean.save()}" ajax="false"/></td>
                <td><p:commandButton id="reset" value="Resetear" action="#{facturaMBean.reset()}" ajax="false"/></td>
             </tr>
         </table>
     </h:form>
     </p:panel>
</body>
</html>

src/web/src/main/webapp/deshabilitar-ruta.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">

 <h:head><title>Paqueteria</title></h:head>
 <body>
    <p:panel header="Deshabilitar ruta">
    <h:form>

    <br/>
        <p:outputLabel for="ruta" value="Tipo de ruta: " />
        <br/>
        <p:selectOneMenu id="ruta" value="#{rutaMBean.ruta}" style="width:150px">
            <f:selectItems value="#{rutaMBean.getRutasHabilitados()}" />
        </p:selectOneMenu>


    <br/>
    <hr/>
    <br/>
        <p:commandButton id="submit" value="Deshabilitar" action="#{rutaMBean.deshabilitar()}" ajax="false"/>

     </h:form>
     </p:panel>
</body>
</html>

src/web/src/main/webapp/error.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"  
     xmlns:h="http://java.sun.com/jsf/html" 
     xmlns:f="http://java.sun.com/jsf/core" 
     xmlns:p="http://primefaces.org/ui">  
   
 <h:head><title>Paqueteria</title></h:head>  
 <body>  
 <f:view>  
     <h:form>  
         <h:outputText value="Error durante la transacción"></h:outputText>  
     </h:form>  
 </f:view>  
</body>    
</html> 

src/web/src/main/webapp/habilitar-paquete.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">

 <h:head><title>Paqueteria</title></h:head>
 <body>
    <p:panel header="Habilitar paquete">
    <h:form>

    <br/>
        <p:outputLabel for="paquete" value="Tipo de paquete: " />
        <br/>
        <p:selectOneMenu id="paquete" value="#{paqueteMBean.paquete}" style="width:150px">
            <f:selectItems value="#{paqueteMBean.getPaquetesDeshabilitados()}" />
        </p:selectOneMenu>


    <br/>
    <hr/>
    <br/>
        <p:commandButton id="submit" value="Habilitar" action="#{paqueteMBean.habilitar()}" ajax="false"/>

     </h:form>
     </p:panel>
</body>
</html>

src/web/src/main/webapp/listar-empleados.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>Paqueteria</title>
</h:head>
<body>
    <h:form>
        <p:dataTable id="empleados" value="#{empleadoMBean.getEmpleados()}" var="empleado" style="width: 100%">
            <p:column>
                <f:facet name="header">
                    <h:outputText value="ID" />
                </f:facet>
                <h:outputText value="#{empleado.id}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Cedula" />
                </f:facet>
                <h:outputText value="#{empleado.cedula}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Nombre" />
                </f:facet>
                <h:outputText value="#{empleado.nombre}" />
            </p:column>
        </p:dataTable>
    </h:form>
</body>
</html>

src/web/src/main/webapp/pagar-factura.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
     xmlns:p="http://primefaces.org/ui">

 <h:head><title>Paqueteria</title></h:head>
 <body>

    <p:panel header="Pagar Factura">
        <h:form id="main">


        <p:dataTable id="factura" var="factura"
            value="#{facturaMBean.facturasPendientes}"
            widgetVar="facturasTable" emptyMessage="Facturas no encontrados con
            ese criterio" filteredValue="#{facturaMBean.filteredFacturas}"
            rows="20" paginator="true" paginatorTemplate="{CurrentPageReport}
            {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink}
            {LastPageLink} {RowsPerPageDropdown}"
            rowsPerPageTemplate="5,10,20,50"
            resizableColumns="false" liveResize="true" selectionMode="single"
            selection="#{facturaMBean.facturaO}" rowKey="#{factura.id}">

            <p:ajax event="rowSelect"
                listener="#{facturaMBean.onFacturaChangeT}"
                update=":main:cliente :main:fecha :main:total :main:guias"/>


            <f:facet name="header">
                <p:outputPanel>
                    <h:outputText value="Factura" />
                    <br/>
                    <br/>
                    <h:outputText value="Buscar en todos los campos:  " />
                    <p:inputText id="globalFilter"
                        onkeyup="PF('facturasTable').filter()"
                        style="width:150px" placeholder="Ingrese palabara"/>
                </p:outputPanel>
            </f:facet>

            <p:column filterBy="#{factura.cliente.ruc_empresa}" headerText="Ruc Empresa"  filterMatchMode="contains">
                    <h:outputText value="#{factura.cliente.ruc_empresa}" />
            </p:column>
            <p:column filterBy="#{factura.cliente.nombre_empresa}" headerText="Empresa"  filterMatchMode="contains">
                    <h:outputText value="#{factura.cliente.nombre_empresa}" />
            </p:column>
            <p:column filterBy="#{factura.valor}" headerText="Valor"  filterMatchMode="contains">
                <h:outputText value="#{factura.valor}" />
            </p:column>
        </p:dataTable>



        <br/>
        <br/>
        <hr/>
        <br/>
        <h2>Detalles de la Factura</h2>



        <br/>
        <br/>
        <h:outputText value="Cliente: "></h:outputText>
        <br/>
        <h:outputText id="cliente" value="#{facturaMBean.empresa}"></h:outputText><br/>

        <br/>
        <br/>
        <h:outputText value="Fecha: "></h:outputText>
        <br/>
        <h:outputText id="fecha" value="#{facturaMBean.fecha}"></h:outputText><br/>

        <br/>
        <br/>
        <h:outputText value="Total: "></h:outputText>
        <br/>
        <h:outputText id="total" value="#{facturaMBean.valor}"></h:outputText><br/>


        <br/>
        <br/>
        <p:dataTable id="guias" value="#{facturaMBean.guiasFactura}" var="guia" style="width: 100%">
            <p:column>
                <f:facet name="header">
                    <h:outputText value="ID" />
                </f:facet>
                <h:outputText value="#{guia.id}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Detalle" />
                </f:facet>
                <h:outputText value="#{guia.detalle}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Paquete" />
                </f:facet>
                <h:outputText value="#{guia.paquete.getDescripcion()}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Ruta" />
                </f:facet>
                <h:outputText value="#{guia.ruta.getDescripcion()}" />
            </p:column>
            <p:column>
                <f:facet name="header">
                    <h:outputText value="Valor" />
                </f:facet>
                <h:outputText value="#{guia.getValor()}" />
            </p:column>
        </p:dataTable>


    <br/>
    <hr/>
    <br/>
        <p:commandButton id="submit" value="Pagar" action="#{facturaMBean.pagar()}" ajax="false"/>

     </h:form>
     </p:panel>
</body>
</html>